com.jack.motorbikestatistics.BTConnection Class Reference
Thread class for a new bluetooth connection to a device.
Public Member Functions
BTConnection (BluetoothDevice btDevice) throws IOException
Constructor for BTConnection class.
void setRXHandler (Handler newHandler)
Setter function for RXHandler.
void run ()
Main run procedure for new Runnable thread created.
void stop ()
Procedure to stop the bluetooth connection thread from running.
boolean isRunning ()
Function to check whether main connection thread is running.
boolean isConnected ()
Function to check whether BT connection is still valid.
Public Attributes
final Handler txHandler
Handler class for transmission of data.
Private Member Functions
void connect () throws IOException
Procedure to create a connection to logging device.
void close () throws IOException
Closes the BT connection socket, exceptions thrown on failure.
Private Attributes
BluetoothDevice btDevice
Bluetooth Device object, holds information for chosen slave.
Handler RXHandler = null
Handler function where received data is sent to.
BluetoothSocket btSocket = null
Socket created for bluetooth connection, used for TX/RX.
volatile boolean running = false
Indicates whether main run thread is in progress.
Static Private Attributes
static final String TAG = `BTConnection`
Tag using for debugging.
static final UUID uuid = UUID.fromString(`00001101-0000-1000-8000-00805f9b34fb`)
UUID to allow Serial connection via BT.
static final String NEW_LINE = `\r\n`
New line string.
Detailed Description
Thread class for a new bluetooth connection to a device.
Constructor & Destructor Documentation
BTConnection()
com.jack.motorbikestatistics.BTConnection.BTConnection (BluetoothDevice btDevice) throws IOException [inline]
Constructor for BTConnection class.
Sets the BT device interface used for this class and attempts a connection.
Parameters
btDevice - Device used for creating connection.
References com.jack.motorbikestatistics.BTConnection.btDevice, and com.jack.motorbikestatistics.BTConnection.connect().
                               {
        this.btDevice = btDevice;
        /* Connect the device so ready to use run */
        connect();
    }
Member Function Documentation
setRXHandler()
void com.jack.motorbikestatistics.BTConnection.setRXHandler (Handler newHandler) [inline]
Setter function for RXHandler.
Parameters
newHandler - The new Handler where RX'd data will be sent to.
                                                 {
        RXHandler = newHandler;
    }
run()
void com.jack.motorbikestatistics.BTConnection.run () [inline]
Main run procedure for new Runnable thread created.
If connected procedure waits for data to be received. Parsing this received into lines and then splitting each line into a JSONObject. If a valid JSONObject is found it is then sends to the receive handler in a seperate thread (using messages).
References com.jack.motorbikestatistics.BTConnection.close(), com.jack.motorbikestatistics.BTConnection.isConnected(), and com.jack.motorbikestatistics.BTConnection.isRunning().
                      {
        InputStream RXStream;
        /* Indicate that we are now running main thread */
        running = true;
        if (isConnected()) {
            /* Get our input stream for receiving bytes */
            try {
                RXStream = btSocket.getInputStream();
            } catch (IOException e) {
                Log.e(TAG, "Unable to get RXStream", e);
                running = false;
                return;
            }
            /*
             * While still connected and not signalled to stop we receive data
             * and then send it to the handler
             */
            String recvBuff = "";
            while (isRunning() && isConnected()) {
                try {
                    int bytesAvailable = RXStream.available();
                    if (bytesAvailable > 0) {
                        byte[] packetBytes = new byte[bytesAvailable];
                        int bytesRead = RXStream.read(packetBytes, 0, bytesAvailable);
                        recvBuff += new String(packetBytes);
                    }
                    if (RXHandler != null) {
                        if (recvBuff.indexOf(NEW_LINE) > 0) {
                            String jsonLine = recvBuff.substring(0, recvBuff.indexOf(
      NEW_LINE));
                            /*
                             * Having to send data to main thread using messages
                             * as we are multithreading.
                             * If we try and use a standard call to function
                             * will cause a crash.
                             */
                            Bundle dataBundle = new Bundle();
                            dataBundle.putString("JSON", jsonLine);
                            Message message = RXHandler.obtainMessage();
                            message.setData(dataBundle);
                            message.sendToTarget();
                            recvBuff = recvBuff.replace(jsonLine + NEW_LINE, "");
                        }
                    }
                } catch (IOException e) {
                    Log.e(TAG, "Unable to read data", e);
                    running = false;
                    return;
                }
            }
        }
        /* Close bluetooth socket */
        try {
            this.close();
        } catch (IOException e) {
            /* Do nothing */
        }
        /* Null BT socket to show needs to reconnect */
        btSocket = null;
        running = false;
    }
isRunning()
boolean com.jack.motorbikestatistics.BTConnection.isRunning () [inline]
Function to check whether main connection thread is running.
Returns
boolean - Whether thread is running.
References com.jack.motorbikestatistics.BTConnection.running.
                               {
        return running;
    }
isConnected()
boolean com.jack.motorbikestatistics.BTConnection.isConnected () [inline]
Function to check whether BT connection is still valid.
Returns
boolean - Whether connection is still available.
                                 {
        boolean result = false;
        if (btSocket != null) {
            if (btSocket.isConnected())
                result = true;
        }
        return result;
    }
connect()
void com.jack.motorbikestatistics.BTConnection.connect () throws IOException [inline], [private]
Procedure to create a connection to logging device.
Creates a raw Serial socket via UUID and then attempts to connect. Exceptions thrown on failure.
References com.jack.motorbikestatistics.BTConnection.close().
                                              {
        /* Attempt to make connection to remote device, throw exception if not */
        try {
            btSocket = btDevice.createRfcommSocketToServiceRecord(
      uuid);
        } catch (IOException e) {
            Log.e(TAG, "Unable to create RFCOMM", e);
            throw e;
        }
        try {
            btSocket.connect();
        } catch (IOException e) {
            Log.e(TAG, "Unable to connect", e);
            /* Close our socket as unable to connect */
            try {
                this.close();
            } catch (IOException e2) {
                throw e2;
            }
            throw e;
        }
    }
Member Data Documentation
txHandler
final Handler com.jack.motorbikestatistics.BTConnection.txHandler
Initial value:
= new Handler(Looper.getMainLooper()) {
        
        @Override
        public void handleMessage(Message msg) {
            
            if (isConnected() && isRunning()) {
                OutputStream TXStream;
                
                try {
                    TXStream = btSocket.getOutputStream();
                    String txString = (String)msg.obj;
                    TXStream.write(txString.getBytes());
                } catch (IOException e) {
                    Log.e(TAG, "Unable to use TXStream", e);
                    return;
                }
            }
        }
    }
Handler class for transmission of data.
Messages containing data to be transmitted are sent from main UI thread.
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/BTConnection.java