com.jack.motorbikestatistics.DataItem< T > Class Template Reference
Class used for holding and displaying a piece of data within the statistic ListView UI.
Public Member Functions
DataItem (String name, boolean avgMinMax)
Constructor for creation of a DataItem.
DataItem (String name, boolean avgMinMax, T value)
Constructor for creation of a DataItem.
String getName ()
Getter for name of data item.
boolean getEnabledAvgMinMax ()
Getter for whether additional functionality enabled.
T getCurrent ()
Getter for current reading value.
Double getAverage ()
Getter for average of readings.
T getMinimum ()
Getter for minimum of readings.
T getMaximum ()
Getter for maximum of readings.
void setCurrent (T value)
Setter for current reading value.
Private Member Functions
Double add (Number a, Number b)
Function to allow addition of numbers with variable types.
Double divide (Number numerator, Number denominator)
Function to allow division of numbers with variable types.
boolean greaterThan (Number a, Number b)
Function to chcek whether A is greater than B.
boolean lessThan (Number a, Number b)
Function to chcek whether A is less than B.
Private Attributes
String name
The name of the statistic.
boolean enableAvgMinMax
Whether averaging, min & max values should be calculated.
T current = null
Current reading value.
Double average = 0.0
Average reading value.
Double averageSum = 0.0
Sum of all readings, used for averaging.
int averageCount = 0
Number of readings, used for averaging.
T minimum = null
Minimum reading value.
T maximum = null
Maximum reading value.
Detailed Description
Class used for holding and displaying a piece of data within the statistic ListView UI.
Constructor & Destructor Documentation
DataItem() [1/2]
com.jack.motorbikestatistics.DataItem< T >.DataItem (String name, boolean avgMinMax) [inline]
Constructor for creation of a DataItem.
Sets up the name of the data item as well as Whether averaging, minimum and maximum readings will be used
Parameters
name - Name of the data item.
avgMinMax - Whether additive functionality shall be available.
References com.jack.motorbikestatistics.DataItem< T >.name.
                                                    {
        this.name = name;
        this.enableAvgMinMax = avgMinMax;
    }
DataItem() [2/2]
com.jack.motorbikestatistics.DataItem< T >.DataItem (String name, boolean avgMinMax, T value) [inline]
Constructor for creation of a DataItem.
Similar to other constructor however allows setting of an initial value.
Parameters
name - Name of the data item.
avgMinMax - Whether additive functionality shall be available.
value - Initial reading value.
References com.jack.motorbikestatistics.DataItem< T >.name.
                                                             {
        this.name = name;
        this.enableAvgMinMax = avgMinMax;
        this.current = value;
        if ((avgMinMax) && (current instanceof Number)) {
            this.average = (Double)value;
            this.averageSum = (Double)value;
            this.averageCount++;
            this.minimum = value;
            this.maximum = value;
        }
    }
Member Function Documentation
getName()
String com.jack.motorbikestatistics.DataItem< T >.getName () [inline]
Getter for name of data item.
Returns
String - DataItem name.
References com.jack.motorbikestatistics.DataItem< T >.name.
                            {
        return name;
    }
getEnabledAvgMinMax()
boolean com.jack.motorbikestatistics.DataItem< T >.getEnabledAvgMinMax () [inline]
Getter for whether additional functionality enabled.
Returns
boolean - Averaging, Minimum & Maximum enabled.
References com.jack.motorbikestatistics.DataItem< T >.enableAvgMinMax.
                                         {
        return enableAvgMinMax;
    }
getCurrent()
T com.jack.motorbikestatistics.DataItem< T >.getCurrent () [inline]
Getter for current reading value.
Returns
T - Current reading value.
References com.jack.motorbikestatistics.DataItem< T >.current.
                          {
        return current;
    }
getAverage()
Double com.jack.motorbikestatistics.DataItem< T >.getAverage () [inline]
Getter for average of readings.
Returns
Double - Average of all readings.
References com.jack.motorbikestatistics.DataItem< T >.average.
                               {
        return average;
    }
getMinimum()
T com.jack.motorbikestatistics.DataItem< T >.getMinimum () [inline]
Getter for minimum of readings.
Returns
T - Minimum value.
References com.jack.motorbikestatistics.DataItem< T >.minimum.
                          {
        return minimum;
    }
getMaximum()
T com.jack.motorbikestatistics.DataItem< T >.getMaximum () [inline]
Getter for maximum of readings.
Returns
T - Maximum value.
References com.jack.motorbikestatistics.DataItem< T >.maximum.
                          {
        return maximum;
    }
setCurrent()
void com.jack.motorbikestatistics.DataItem< T >.setCurrent (T value) [inline]
Setter for current reading value.
If additive functionality enabled and the reading is of types number then we go ahead and update our min, max & average values as well will the passed in new reading.
Parameters
T - New reading.
References com.jack.motorbikestatistics.DataItem< T >.add(), com.jack.motorbikestatistics.DataItem< T >.current, com.jack.motorbikestatistics.DataItem< T >.divide(), com.jack.motorbikestatistics.DataItem< T >.greaterThan(), and com.jack.motorbikestatistics.DataItem< T >.lessThan().
                                    {
        this.current = value;
        if ((enableAvgMinMax) && (current instanceof Number)) {
            /* Sets the average */
            averageCount++;
            averageSum = add(averageSum, (Number)value);
            average = divide(averageSum, averageCount);
            /* Sets the new minimum and maximums if true */
            if ((minimum == null) || lessThan((Number)current, (Number)
      minimum)) {
                minimum = current;
            }
            if ((maximum == null) || greaterThan((Number)current, (Number)
      maximum)) {
                maximum = current;
            }
        }
    }
add()
Double com.jack.motorbikestatistics.DataItem< T >.add (Number a, Number b) [inline], [private]
Function to allow addition of numbers with variable types.
Parameters
a - First operand.
b - Second operand.
Returns
Double - Sum.
                                           {
        return new Double(a.doubleValue() + b.doubleValue());
    }
divide()
Double com.jack.motorbikestatistics.DataItem< T >.divide (Number numerator, Number denominator) [inline], [private]
Function to allow division of numbers with variable types.
Parameters
numerator - Numerator of divisior.
denominator - Denominator of divisor.
Returns
Double - Result of division.
                                                                {
        return new Double(numerator.doubleValue() / denominator.doubleValue());
    }
greaterThan()
boolean com.jack.motorbikestatistics.DataItem< T >.greaterThan (Number a, Number b) [inline], [private]
Function to chcek whether A is greater than B.
Parameters
a - First operand.
b - Second operand.
Returns
boolean - Whether A is greater than B.
                                                    {
        return a.doubleValue() > b.doubleValue();
    }
lessThan()
boolean com.jack.motorbikestatistics.DataItem< T >.lessThan (Number a, Number b) [inline], [private]
Function to chcek whether A is less than B.
Parameters
a - First operand.
b - Second operand.
Returns
boolean - Whether A is less than B.
                                                 {
        return a.doubleValue() < b.doubleValue();
    }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/DataItem.java