com.jack.motorbikestatistics.BTDeviceListAdapter Class Reference
Adapter class used for displaying bluetooth devices.
Classes
class ViewHolder
Class that holds all data displayed for each ListItem.
Public Member Functions
BTDeviceListAdapter (Context cnt, int layoutResourceId, ArrayList< BTDeviceItem > data)
Constructor for the ListView adapter.
View getView (int position, View convertView, ViewGroup parent)
Function for returning the view of each list item (BTDeviceItem).
Private Attributes
int layoutResourceId
Resource ID for current layout.
Context context
Context that the ListView is operating in.
ArrayList< BTDeviceItem > data
ArrayList of all bluetooth device items to display.
Detailed Description
Adapter class used for displaying bluetooth devices.
Constructor & Destructor Documentation
BTDeviceListAdapter()
com.jack.motorbikestatistics.BTDeviceListAdapter.BTDeviceListAdapter (Context cnt, int layoutResourceId, ArrayList< BTDeviceItem > data) [inline]
Constructor for the ListView adapter.
Calls the constructor of the superclass as well as setting other relevant information needed.
Parameters
cnt - Context of the adapter to be operating in.
layoutResourceId - Resource ID for current layout.
data - ArrayList of devices to display in ListView.
References com.jack.motorbikestatistics.BTDeviceListAdapter.data, and com.jack.motorbikestatistics.BTDeviceListAdapter.layoutResourceId.
                                                                                                {
        super(cnt, layoutResourceId, data);
        this.context = cnt;
        this.layoutResourceId = layoutResourceId;
        this.data = data;
    }
Member Function Documentation
getView()
View com.jack.motorbikestatistics.BTDeviceListAdapter.getView (int position, View convertView, ViewGroup parent) [inline]
Function for returning the view of each list item (BTDeviceItem).
If a view for selected item has not been created inflater initialises it. A holder is then used to hold all the information that will be displayed on the UI to the user.
Parameters
position - Index of item in array to use/reference to.
convertView - View to be used for specified item.
parent - Object where the created view will be placed on.
Returns
View - The result view of item with updated/current information.
References com.jack.motorbikestatistics.BTDeviceItem.getDevice(), com.jack.motorbikestatistics.BTDeviceItem.getIconID(), and com.jack.motorbikestatistics.BTDeviceItem.getStatus().
                                                                          {
        ViewHolder holder;
        if (convertView == null)
        {
            /* Create new view via inflater as it does not exist. */
            LayoutInflater inflater = (LayoutInflater)context.getSystemService(Context.
      LAYOUT_INFLATER_SERVICE);
            convertView = inflater.inflate(layoutResourceId, parent, false);
            /* Create holder that will contain information to display. */
            holder = new ViewHolder();
            holder.imageStatus = (ImageView)convertView.findViewById(R.id.imageListStatus);
            holder.name = (TextView)convertView.findViewById(R.id.textListName);
            holder.address = (TextView)convertView.findViewById(R.id.textListAddress);
            holder.status = (TextView)convertView.findViewById(R.id.textListStatus);
            convertView.setTag(holder);
        }
        else
        {
            /* Get current holder to use instead of creating new one. */
            holder = (ViewHolder)convertView.getTag();
        }
        /* Get BTDeviceItem for specified item and update holder info. */
        BTDeviceItem btItem = getItem(position);
        holder.imageStatus.setImageResource(btItem.getIconID());
        holder.name.setText(btItem.getDevice().getName());
        holder.address.setText(btItem.getDevice().getAddress());
        holder.status.setText(btItem.getStatus());
        return convertView;
    }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/BTDeviceListAdapter.java