com.jack.motorbikestatistics.LoadDeviceFragment.TripItemListener Class Reference
Listener used to identify when a trip has been pressed.
Public Member Functions
void onItemClick (AdapterView<?> parent, View view, int position, long id)
Loads a trip the user has specified.
Detailed Description
Listener used to identify when a trip has been pressed.
Member Function Documentation
onItemClick()
void com.jack.motorbikestatistics.LoadDeviceFragment.TripItemListener.onItemClick (AdapterView<?> parent, View view, int position, long id) [inline]
Loads a trip the user has specified.
User has selected a trip via the ListView, method switches to the statistic fragment and sends a message to logging device to load the specified trip (via name).
References com.jack.motorbikestatistics.TripItem.getTripName(), com.jack.motorbikestatistics.BTConnection.isConnected(), com.jack.motorbikestatistics.RealtimeFragment.RXHandler, com.jack.motorbikestatistics.BTConnection.setRXHandler(), and com.jack.motorbikestatistics.BTConnection.txHandler.
                                                                                         {
            if (btConnection != null && btConnection.
      isConnected()) {
                TripItem tripItem = (TripItem) parent.getItemAtPosition(position);
                /*
                 * Create a new statistics fragment.
                 * This will receive the stored data from the logging device.
                 */
                RealtimeFragment statFragment = new RealtimeFragment();
                btConnection.setRXHandler(statFragment.RXHandler);
                /* Transmit over the name of the trip we want to load */
                Message message = new Message();
                message.obj = (String) LOAD_TRIP_CHAR + tripItem.getTripName();
                message.setTarget(btConnection.txHandler);
                message.sendToTarget();
                FragmentManager fragmentManager = getFragmentManager();
                fragmentManager.beginTransaction()
                        .replace(R.id.content_frame, statFragment)
                        .commit();
            }
        }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/LoadDeviceFragment.java