com.jack.motorbikestatistics.PairDeviceFragment Class Reference
UI Class for discovering, pairing and connecting to the logging device.
Classes
class DeviceItemListener
Listener for when a ListView item is pressed (to connect).
class DiscoverButtonListener
Listener for when discovery button is pressed.
class DiscoverReceiver
Receiver for when a new device is discovered.
Public Member Functions
PairDeviceFragment ()
Constructor for UI fragment.
View onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
Function called when fragment is shown on UI.
BTConnection getBTConnection ()
Getter for getting current connected device.
Private Member Functions
void getNeededPrivileges ()
Prompts user for needed permissions of this application.
Private Attributes
boolean firstRun = true
Check variable used to stop ListView from being re-populated.
ToggleButton btnScan
Scan button, used for toggling discovery.
BluetoothAdapter btAdapter = null
Mobile's bluetooth adapter.
ArrayList< BTDeviceItem > btDeviceList
List of all devices, unpaired, paired & connected.
ArrayList< BTDeviceItem > btPairedList
List of only paired devices.
ArrayAdapter< BTDeviceItem > lvAdapter
UI adapter for ListView that displays bluetooth devices.
BTDeviceItem btConnectedDevice = null
Applications connected logging device.
DiscoverReceiver btReceiver = null
Receiver class for when new device discovered.
Static Private Attributes
static final int REQUEST_BLUETOOTH = 1
Request code for activating bluetooth.
static final String CONNECTED_STATUS = `connected`
Status to change BTDeviceItem to when connected.
static final int BT_DISABLED_ICON = R.drawable.ic_bluetooth_disabled_black_24px
Icon ID to use when device is not connected.
Detailed Description
UI Class for discovering, pairing and connecting to the logging device.
Constructor & Destructor Documentation
PairDeviceFragment()
com.jack.motorbikestatistics.PairDeviceFragment.PairDeviceFragment () [inline]
Constructor for UI fragment.
Get's the mobile's bluetooth adapter and sets up our lists of used for holding devices.
    {
        /* Get bluetooth adapter for device & create device arrays */
        btAdapter = BluetoothAdapter.getDefaultAdapter();
        btDeviceList = new ArrayList<BTDeviceItem>();
        btPairedList = new ArrayList<BTDeviceItem>();
        btReceiver = new DiscoverReceiver();
    }
Member Function Documentation
onCreateView()
View com.jack.motorbikestatistics.PairDeviceFragment.onCreateView (LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) [inline]
Function called when fragment is shown on UI.
Sets up the UI ListView and Buttons. Add all paired devices for the bluetooth adapter to the ListView.
Parameters
inflater - Inflater used for displaying view.
container - Container that the view will be displayed on.
savedInstanceState - Last known state of this fragment.
Returns
View - The UI view of this fragment.
References com.jack.motorbikestatistics.BTDeviceItem.getConnection(), com.jack.motorbikestatistics.PairDeviceFragment.getNeededPrivileges(), com.jack.motorbikestatistics.BTConnection.isConnected(), and com.jack.motorbikestatistics.BTConnection.isRunning().
                                                                                                      {
        View myView = inflater.inflate(R.layout.pairdevice_layout, container, false);
        /* Request needed privileges for bluetooth to work */
        getNeededPrivileges();
        /* Set our variables for UI buttons */
        btnScan = (ToggleButton)myView.findViewById(R.id.pairdevice_search);
        btnScan.setOnCheckedChangeListener(new DiscoverButtonListener());
        ListView lvDevices = (ListView)myView.findViewById(R.id.pairdevice_deviceList);
        lvDevices.setOnItemClickListener(new DeviceItemListener());
        lvAdapter = new BTDeviceListAdapter(getActivity(), R.layout.device_list_item,
      btDeviceList);
        lvDevices.setAdapter(lvAdapter);
        /* Check and set up bluetooth adapter */
        if (btAdapter == null)
        {
            Toast.makeText(getActivity().getApplicationContext(),
                    "This device has no bluetooth adapter", Toast.LENGTH_LONG).show();
        }
        else
        {
            /* Check to see if connected device still is connected */
            if (btConnectedDevice != null)
            {
                if (!btConnectedDevice.getConnection().
      isConnected() ||
                        !btConnectedDevice.getConnection().
      isRunning())
                {
                    btConnectedDevice = null;
                }
            }
            /* firstRun check to list from being re-populated */
            if (firstRun)
            {
                firstRun = false;
                /* Enable bluetooth adapter if disabled */
                if (!btAdapter.isEnabled())
                {
                    Intent enableBT = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
                    startActivityForResult(enableBT, REQUEST_BLUETOOTH);
                }
                while (!btAdapter.isEnabled())
                {
                    /* Wait for BT to be enabled */
                }
                /* Add all paired devices to list */
                Set<BluetoothDevice> pairedDevices = btAdapter.getBondedDevices();
                if (pairedDevices.size() > 0)
                {
                    for (BluetoothDevice device : pairedDevices)
                    {
                        BTDeviceItem newDevice =
                            new BTDeviceItem(device, "paired", BT_DISABLED_ICON);
                        btPairedList.add(newDevice);
                    }
                }
                btDeviceList.addAll(btPairedList);
            }
        }
        return myView;
    }
getBTConnection()
BTConnection com.jack.motorbikestatistics.PairDeviceFragment.getBTConnection () [inline]
Getter for getting current connected device.
Returns
BTConnection - Bluetooth device (logging device).
References com.jack.motorbikestatistics.BTDeviceItem.getConnection().
    {
        if (btConnectedDevice != null) {
            return btConnectedDevice.getConnection();
        } else {
            return null;
        }
    }
getNeededPrivileges()
void com.jack.motorbikestatistics.PairDeviceFragment.getNeededPrivileges () [inline], [private]
Prompts user for needed permissions of this application.
Due to android using a permissions/access method this method parses through each permission needed and prompts the user to accept.
    {
        final int REQUEST_CODE = 5;
        boolean permsGranted = true;
        String[] permsToRequest =
                {
                        Manifest.permission.BLUETOOTH_ADMIN,
                        Manifest.permission.BLUETOOTH,
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.ACCESS_COARSE_LOCATION
                };
        for (String permission: permsToRequest)
        {
            permsGranted &= (ContextCompat.checkSelfPermission(getActivity(), permission) == PackageManager
      .PERMISSION_GRANTED);
        }
        if (!permsGranted)
        {
            ActivityCompat.requestPermissions(getActivity(), permsToRequest, REQUEST_CODE);
        }
    }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/PairDeviceFragment.java