com.jack.motorbikestatistics.DataListAdapter Class Reference
Adapter class used for displaying statistics.
Classes
class ViewHolder
Class that holds all data displayed for each ListItem.
Public Member Functions
DataListAdapter (Context cnt, int layoutResourceId, ArrayList< DataItem > data)
Constructor for the ListView adapter.
View getView (int position, View convertView, ViewGroup parent)
Function for returning the view of each list item (DataItem).
Private Attributes
Context context
Context that the ListView is operating in.
int layoutResourceId
Resource ID for current layout.
ArrayList< DataItem > data
ArrayList of all statistic items to display.
Detailed Description
Adapter class used for displaying statistics.
Constructor & Destructor Documentation
DataListAdapter()
com.jack.motorbikestatistics.DataListAdapter.DataListAdapter (Context cnt, int layoutResourceId, ArrayList< DataItem > data) [inline]
Constructor for the ListView adapter.
Calls the constructor of the superclass as well as setting other relevant information needed.
Parameters
cnt - Context of the adapter to be operating in.
layoutResourceId - Resource ID for current layout.
data - ArrayList of statistics to display in ListView.
References com.jack.motorbikestatistics.DataListAdapter.data, and com.jack.motorbikestatistics.DataListAdapter.layoutResourceId.
                                                                                        {
        super(cnt, layoutResourceId, data);
        this.context = cnt;
        this.layoutResourceId = layoutResourceId;
        this.data = data;
    }
Member Function Documentation
getView()
View com.jack.motorbikestatistics.DataListAdapter.getView (int position, View convertView, ViewGroup parent) [inline]
Function for returning the view of each list item (DataItem).
If a view for selected item has not been created inflater initialises it. A holder is then used to hold all the information that will be displayed on the UI to the user.
Parameters
position - Index of item in array to use/reference to.
convertView - View to be used for specified item.
parent - Object where the created view will be placed on.
Returns
View - The result view of item with updated/current information.
References com.jack.motorbikestatistics.DataItem< T >.getAverage(), com.jack.motorbikestatistics.DataItem< T >.getCurrent(), com.jack.motorbikestatistics.DataItem< T >.getEnabledAvgMinMax(), com.jack.motorbikestatistics.DataItem< T >.getMaximum(), com.jack.motorbikestatistics.DataItem< T >.getMinimum(), and com.jack.motorbikestatistics.DataItem< T >.getName().
                                                                          {
        ViewHolder holder;
        if (convertView == null)
        {
            /* If view does not already exist. */
            LayoutInflater inflater = (LayoutInflater)context.getSystemService(Context.
      LAYOUT_INFLATER_SERVICE);
            convertView = inflater.inflate(layoutResourceId, parent, false);
            holder = new ViewHolder();
            holder.name = (TextView)convertView.findViewById(R.id.datalist_name);
            holder.current = (TextView)convertView.findViewById(R.id.datalist_current);
            holder.average = (TextView)convertView.findViewById(R.id.datalist_average);
            holder.minimum = (TextView)convertView.findViewById(R.id.datalist_minimum);
            holder.maximum = (TextView)convertView.findViewById(R.id.datalist_maximum);
            convertView.setTag(holder);
        }
        else
        {
            /* If view already exists. */
            holder = (ViewHolder)convertView.getTag();
        }
        DataItem dataItem = getItem(position);
        /* Set our holder with current data of item */
        holder.name.setText(dataItem.getName());
        Object current = dataItem.getCurrent();
        if (current != null) {
            DecimalFormat df = new DecimalFormat("#.####");
            df.setRoundingMode(RoundingMode.CEILING);
            /* To aid aesthetics rounding is used. */
            if (current instanceof Double) {
                holder.current.setText(df.format(current));
            } else {
                holder.current.setText(current.toString());
            }
            /*
             * Displays added functionality if available.
             * Not all statistics need it, for example averaging of LAT/LNG.
             */
            if (dataItem.getEnabledAvgMinMax()) {
                holder.average.setText(df.format(dataItem.getAverage()));
                holder.minimum.setText(df.format(dataItem.getMinimum()));
                holder.maximum.setText(df.format(dataItem.getMaximum()));
            } else {
                holder.average.setText("N/A");
                holder.minimum.setText("N/A");
                holder.maximum.setText("N/A");
            }
        }
        return convertView;
    }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/DataListAdapter.java