com.jack.motorbikestatistics.PairDeviceFragment.DeviceItemListener Class Reference
Listener for when a ListView item is pressed (to connect).
Public Member Functions
void onItemClick (AdapterView<?> parent, View view, int position, long id)
Function called when user wants to connect to a device.
Detailed Description
Listener for when a ListView item is pressed (to connect).
Member Function Documentation
onItemClick()
void com.jack.motorbikestatistics.PairDeviceFragment.DeviceItemListener.onItemClick (AdapterView<?> parent, View view, int position, long id) [inline]
Function called when user wants to connect to a device.
Discovery is turned off to stop power wastage. A new connection thread is then created which is responsible for parsing receive, and transmission requests from other fragments.
Parameters
parent - The parent ListView.
view - Current view of the ListItem.
position - Index of item pressed in ListView.
id - ID of the ListItem.
References com.jack.motorbikestatistics.BTDeviceItem.getConnection(), com.jack.motorbikestatistics.BTDeviceItem.getDevice(), com.jack.motorbikestatistics.BTConnection.isConnected(), com.jack.motorbikestatistics.BTDeviceItem.setConnection(), com.jack.motorbikestatistics.BTDeviceItem.setIconID(), and com.jack.motorbikestatistics.BTDeviceItem.setStatus().
                                                                                         {
            BTDeviceItem deviceItem = (BTDeviceItem)parent.getItemAtPosition(position);
            /* Check if there is already a connection between devices */
            if ((deviceItem.getConnection() == null) ||
                    (!deviceItem.getConnection().isConnected()))
            {
                if (btAdapter.isDiscovering())
                {
                    /* Cancel discovery is still enabled */
                    btnScan.setChecked(false);
                    btAdapter.cancelDiscovery();
                }
                try
                {
                    Toast.makeText(parent.getContext(), "Connecting to: " +
                            deviceItem.getDevice().getName(), Toast.LENGTH_SHORT).show();
                    /* Create a new BTConnection item with no RX handler */
                    BTConnection newConn = new BTConnection(deviceItem.getDevice());
                    /* Execute the 'run' procedure in object in new thread */
                    Thread tmpThread = new Thread(newConn);
                    tmpThread.start();
                    /* Add set connection and add item to listview */
                    deviceItem.setConnection(newConn);
                    btConnectedDevice = deviceItem;
                    /* Update status and icon in list view */
                    deviceItem.setIconID(R.drawable.ic_bluetooth_connected_black_24px);
                    deviceItem.setStatus(CONNECTED_STATUS);
                    lvAdapter.notifyDataSetChanged();
                }
                catch (IOException e)
                {
                    Toast.makeText(parent.getContext(), "Unable to connect: " +
                            e.toString(), Toast.LENGTH_SHORT).show();
                }
            }
        }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/PairDeviceFragment.java