com.jack.motorbikestatistics.MainActivity Class Reference
Main activity class for fragment navigation.
Public Member Functions
void onBackPressed ()
Responsible for closing navigation drawer when back button pressed.
boolean onNavigationItemSelected (MenuItem item)
Changes active fragment when a tab has been pressed.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
Function called when main activity is loaded.
Static Private Attributes
static final String REALTIME_CHAR = `1`
Command for switching to realtime logging.
static final String LIST_SAVED_CHAR = `2`
Command for loading all saved trip details.
static RealtimeFragment rtFragment = null
UI fragment for realtime statistic display.
static LoadDeviceFragment ldFragment = null
UI fragment for loading previous trips.
static PairDeviceFragment pdFragment = null
UI fragment for pairing to a logging device.
Detailed Description
Main activity class for fragment navigation.
Member Function Documentation
onCreate()
void com.jack.motorbikestatistics.MainActivity.onCreate (Bundle savedInstanceState) [inline], [protected]
Function called when main activity is loaded.
Procedure is called when application is first started, sets up UI and creates relevant fragments.
Parameters
savedInstanceState - Information holding last previous state.
                                                       {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.setDrawerListener(toggle);
        toggle.syncState();
        NavigationView navigationView = (NavigationView) findViewById(R.id.nav_view);
        navigationView.setNavigationItemSelectedListener(this);
        /* Create our fragments for different sections of UI */
        rtFragment = new RealtimeFragment();
        ldFragment = new LoadDeviceFragment();
        pdFragment = new PairDeviceFragment();
    }
onNavigationItemSelected()
boolean com.jack.motorbikestatistics.MainActivity.onNavigationItemSelected (MenuItem item) [inline]
Changes active fragment when a tab has been pressed.
Responsible for changing to the new chosen fragment on the UI. Opening of realtime and loaddevice fragments not possible when not connected to the logging device.
Method also responsible for change system state machine on the logging device, this is done by transmitting command code.
Parameters
item - New selected fragment/tab to display.
References com.jack.motorbikestatistics.PairDeviceFragment.getBTConnection(), com.jack.motorbikestatistics.BTConnection.isConnected(), com.jack.motorbikestatistics.MainActivity.ldFragment, com.jack.motorbikestatistics.MainActivity.pdFragment, com.jack.motorbikestatistics.MainActivity.rtFragment, com.jack.motorbikestatistics.LoadDeviceFragment.RXHandler, com.jack.motorbikestatistics.LoadDeviceFragment.setBTConnection(), com.jack.motorbikestatistics.BTConnection.setRXHandler(), and com.jack.motorbikestatistics.BTConnection.txHandler.
                                                           {
        Fragment activeFragment = null;
        /* Handle navigation view clicks here */
        FragmentManager fragmentManager = getFragmentManager();
        int id = item.getItemId();
        switch (id) {
            case R.id.nav_realtime: {
                /* Get our bluetooth connection from pairing fragment */
                BTConnection btConn = pdFragment.getBTConnection();
                if (btConn != null && btConn.isConnected()) {
                    /* We set our RX handler and also send our command to indicate mode change */
                    btConn.setRXHandler(rtFragment.RXHandler);
                    Message message = new Message();
                    message.obj = (String) REALTIME_CHAR;
                    message.setTarget(btConn.txHandler);
                    message.sendToTarget();
                    /* Change to our new active fragment */
                    activeFragment = rtFragment;
                } else {
                    /* Indicate that we are not connected to device */
                    View rootView = findViewById(R.id.content_main);
                    Snackbar.make(rootView, "Please connect to a device first.", Snackbar.LENGTH_LONG)
                            .setAction("Action", null).show();
                }
                break;
            }
            case R.id.nav_loaddevice: {
                /* Get our bluetooth connection from pairing fragment */
                BTConnection btConn = pdFragment.getBTConnection();
                if (btConn != null && btConn.isConnected()) {
                    /* We set our RX handler and also send our command to indicate mode change */
                    ldFragment.setBTConnection(btConn);
                    btConn.setRXHandler(ldFragment.RXHandler);
                    Message message = new Message();
                    message.obj = (String) LIST_SAVED_CHAR;
                    message.setTarget(btConn.txHandler);
                    message.sendToTarget();
                    /* Change to our new active fragment */
                    activeFragment = ldFragment;
                } else {
                    /* Indicate that we are not connected to device */
                    View rootView = findViewById(R.id.content_main);
                    Snackbar.make(rootView, "Please connect to a device first.", Snackbar.LENGTH_LONG)
                            .setAction("Action", null).show();
                }
                break;
            }
            case R.id.nav_pairdevice: {
                activeFragment = pdFragment;
            }
        }
        if (activeFragment != null) {
            /* Replaces content frame with newly selected one */
            fragmentManager.beginTransaction()
                    .replace(R.id.content_frame, activeFragment)
                    .commit();
        }
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return (activeFragment != null);
    }
The documentation for this class was generated from the following file:
android-app/app/src/main/java/com/jack/motorbikestatistics/MainActivity.java