logging-device/logging-device.ino File Reference
Arduino sketch for the logging device.
#include <SoftwareSerial.h>
#include <TinyGPS++.h>
#include <ArduinoJson.h>
#include `Orientation.h`
#include `Storage.h`
Macros
#define IDLE_CHAR '0'
Command to set system to idle mode.
#define REALTIME_CHAR '1'
Command to set system to realtime logging mode.
#define LIST_SAVED_CHAR '2'
Command to list all saved trip names from uSD.
#define LOAD_TRIP_CHAR '3'
Command to load a trip stored on uSD.
#define BT_SERIAL Serial1
Mapping for which HW-Serial port BT module is on.
#define BT_BAUD 115200
BAUD rate of BT device.
#define GPS_TX_PIN 9
GPS serial transmit pin.
#define GPS_RX_PIN 8
GPS serial receive pin.
#define GPS_BAUD 9600
GPS serial baud rate.
#define LED_PIN 13
LED pin to indicate read.
Enumerations
enum OPERATING_MODE { IDLE,
REALTIME
 }
Typedef holding two possible states for device.
Functions
SoftwareSerial serGPS (GPS_RX_PIN, GPS_TX_PIN)
Serial object for communicating with GPS module.
void setup ()
Runs once at boot of arduino.
void loop ()
Main system loop for arduino.
bool parseNewMode (char modeChar, OPERATING_MODE &newMode)
Returns whether system should change operating mode.
void realTimeMode ()
Responsible for completing work needed in relatime mode.
void addOrientationToJSON ()
Responsible for updating orientation JSON object with newest information.
void addGPSToJSON ()
Responsible for updating GPS JSON object with newest information.
void addTimeToJSON ()
Responsible for updating time JSON object with newest information.
Variables
OPERATING_MODE systemMode = IDLE
State machine for system state of device.
Orientation orientation
Orientation object, used for receiving device orientation.
Storage storage
Storage object, responsible for saving & loading from uSD.
TinyGPSPlus gps
Our GPS object, responsible for parsing NMEA codes.
StaticJsonBuffer< 500 > jsonBuffer
Allocated space for holding all JSON objects within.
JsonObject & mainJSON = jsonBuffer.createObject()
Parent JSON object, holds orientation, time & gps children.
JsonObject & orientJSON = mainJSON.createNestedObject(`orientation`)
Holds all orientation related information.
JsonObject & gpsJSON = mainJSON.createNestedObject(`gps`)
Holds all location related information.
JsonObject & timeJSON = mainJSON.createNestedObject(`time`)
Holds all time related inforamtion.
Detailed Description
Arduino sketch for the logging device.
Author
Jack Allister - 23042098
Date
2016-2017
Arduino 101
Sparkfun GPS Logger shield
Onboard gyroscope + accelerometer
HC-06 Serial Bluetooth Module
Function Documentation
setup()
void setup ()
Runs once at boot of arduino.
Responsible for setting up the peripherals.
Initialises modules such as storage, bluetooth & gps.
References BT_BAUD, BT_SERIAL, GPS_BAUD, Storage::init(), Orientation::init(), LED_PIN, and serGPS().
{
  pinMode(LED_PIN, OUTPUT);
  /* Initialise our created modules */
  storage.init();
  orientation.init();
  /* Set up serial for wireless data transmission */
  BT_SERIAL.begin(BT_BAUD);
  /* Set up serial for GPS module */
  serGPS.begin(GPS_BAUD);
}
loop()
void loop ()
Main system loop for arduino.
Checks serial to see if any commands are available.
If available reads the byte and changes system mode relating to it.
System state machine is also iterated through each loop.
Relevant procedure depending on system state is then called.
References BT_SERIAL, parseNewMode(), and systemMode.
{
  /* Check if mode change character received from front-end */
  if (BT_SERIAL.available() > 0)
  {
    char modeChar = BT_SERIAL.read();
    OPERATING_MODE newMode;
    /* If valid new mode character found change system state */
    if (parseNewMode(modeChar, newMode) == true)
    {
      systemMode = newMode;
    }
  }
  /* State machine for choosing what option takes place */
  switch (systemMode)
  {
    case IDLE:
    {
      /*
       * In IDLE mode MCU does nothing.
       * System waits and still parses incoming commands.
       */
      break;
    }
    case REALTIME:
    {
      realTimeMode();
      break;
    }
  }
}
parseNewMode()
bool parseNewMode (char modeChar, OPERATING_MODE & newMode)
Returns whether system should change operating mode.
Parameters
modeChar - The received command byte
&newMode - Reference to new operating mode calculated via command.
Returns
bool - Whether a valid command was found.
References IDLE_CHAR.
{
  bool result = true;
  switch (modeChar)
  {
    case IDLE_CHAR:
    {
      newMode = IDLE;
      break;
    }
    case REALTIME_CHAR:
    {
      /* Change mode and then generate new file name for new log */
      if (systemMode != REALTIME)
      {
        /* Generate new name if not already in this mode */
        storage.generateFileName();
      }
      newMode = REALTIME;
      break;
    }
    case LIST_SAVED_CHAR:
    {
      /*
       * Load all trips and send to application.
       * Once we have finished sending trips we can go back to idle mode.
       */
      storage.loadTripNames();
      newMode = IDLE;
      break;
    }
    case LOAD_TRIP_CHAR:
    {
      /* Load a specific trip by file name */
      storage.loadSavedTrip();
      newMode = IDLE;
      break;
    }
    default:
    {
      /*
       * If not a valid operating mode character
       * then return that parsing failed.
       */
      result = false;
    }
  }
  return result;
}
realTimeMode()
void realTimeMode ()
Responsible for completing work needed in relatime mode.
Every time called this procedure will poll the IMU to update our orientation class with newest information.
If available NMEA sentences received from GPS serial are sent to our GPS parsing object.
 Every 1000ms all current information is transmitted via bluetooth, this information is also stored to the uSD so it can be retrieved at a later point.
References addGPSToJSON(), addOrientationToJSON(), addTimeToJSON(), BT_SERIAL, gps, LED_PIN, mainJSON, Orientation::pollIMU(), Storage::saveToFile(), and serGPS().
{
  static const unsigned int MAX_STRING_SIZE = 512;
  static const unsigned long PRINT_DELAY = 1000;
  static unsigned long lastMillis = 0;
  char jsonString[MAX_STRING_SIZE];
  /* Poll our IMU to update XYZ */
  orientation.pollIMU();
  /* Parse NMEA codes into GPS object */
  while (serGPS.available() > 0)
  {
    gps.encode(serGPS.read());
  }
  /* Print orientation and location information */
  if ((millis() - lastMillis) > PRINT_DELAY)
  {
    digitalWrite(LED_PIN, HIGH);
    addOrientationToJSON();
    addGPSToJSON();
    addTimeToJSON();
    /* Print our json object into a string */
    mainJSON.printTo(jsonString, MAX_STRING_SIZE);
    /* Log JSON to the microSD */
    storage.saveToFile(jsonString, true);
    /* Print to our bluetooth module */
    BT_SERIAL.println(jsonString);
    lastMillis = millis();
    digitalWrite(LED_PIN, LOW);
  }
}
addOrientationToJSON()
void addOrientationToJSON ()
Responsible for updating orientation JSON object with newest information.
Interacts with devices Orientation object to get Yaw, Pitch & Roll.
References Orientation::getPitch(), Orientation::getRoll(), and Orientation::getYaw().
{
  orientJSON["yaw"] = orientation.getYaw();
  orientJSON["pitch"] = orientation.getPitch();
  orientJSON["roll"] = orientation.getRoll();
}
addGPSToJSON()
void addGPSToJSON ()
Responsible for updating GPS JSON object with newest information.
Interacts with devices TinyGPSPlus object to get all locational/gps related information. Floats are cat'd to 6 digits max.
References gps.
{
  /* Add location information */
  gpsJSON["gps_valid"] = gps.location.isUpdated();
  gpsJSON["lat"] = double_with_n_digits(gps.location.lat(), 6);
  gpsJSON["lng"] = double_with_n_digits(gps.location.lng(), 6);
  /* Other crucial GPS information */
  gpsJSON["available"] = gps.satellites.value();
  gpsJSON["vel_mph"] = gps.speed.mph();
  gpsJSON["alt_ft"] = gps.altitude.feet();
}
addTimeToJSON()
void addTimeToJSON ()
Responsible for updating time JSON object with newest information.
Interacts with devices TinyGPSPlus object to get time related information. This is because GPS module has a RTC (Realtime-Clock) kept via NMEA sentences.
References gps.
{
  /* Add time information to JSON */
  timeJSON["time_valid"] = gps.date.isValid() && gps.time.isValid();
  timeJSON["day"] = gps.date.day();
  timeJSON["month"] = gps.date.month();
  timeJSON["year"] = gps.date.year();
  timeJSON["hour"] = gps.time.hour();
  timeJSON["minute"] = gps.time.minute();
  timeJSON["second"] = gps.time.second();
  timeJSON["centiseconds"] = gps.time.centisecond();
}